package com.cb.mundo.model.entity.enumeration;



/**
 * Papeis para staff.
 * [18.05.2012] ordem alfabetica
 * 
 * @author Solkam
 * @since 12 NOV 2012
 */
public enum StaffRole {
	
	WATER("PRODUCTION_STAFF_ROLE_WATER")//Agua
	,WAREHOUSE("PRODUCTION_STAFF_ROLE_WAREHOUSE")//Almoxarifado
	,COORD_ASSIST("PRODUCTION_STAFF_ROLE_COORDINATOR_ASSISTENT")//Apoio Coordenador Geral
	,EXTERNAL_ASSIST("PRODUCTION_STAFF_ROLE_EXTERNAL_ASSISTENT")//Apoio Externo
	,FINANCIAL_ASSIST("PRODUCTION_STAFF_ROLE_FINANCIAL_ASSISTENT")//Apoio Financeiro
	,AIR("PRODUCTION_STAFF_ROLE_AIR")//Ar Condicionado
	,EXCAP_ASSIST("PRODUCTION_STAFF_ROLE_EXTCAPTAIN_ASSISTENT")//Assistente Capitao Externo
	,INCAP_ASSIST("PRODUCTION_STAFF_ROLE_INTCAPTAIN_ASSISTENT")//Assitente Capitao Interno
	,FAC_ASSIST("PRODUCTION_STAFF_ROLE_FACILITATOR_ASSISTENT")//Assistente Facilitator
	,TIMER_ASSIST("PRODUCTION_STAFF_ROLE_TIMER_ASSISTENT")//Assistente Timer
	,BOOKSHOP("PRODUCTION_STAFF_ROLE_BOOKSHOP")//Bookshop
	,MATERIAL("PRODUCTION_STAFF_ROLE_MATERIAL")//Caixa de Materiais
	,EXCAP("PRODUCTION_STAFF_ROLE_EXTCAPTAIN")//Capitao Externo
	,INCAP("PRODUCTION_STAFF_ROLE_INTCAPTAIN")//Capitao Interno
	,COORD("PRODUCTION_STAFF_ROLE_COORDINATOR")//Coordenador Geral
	,JOKER("PRODUCTION_STAFF_ROLE_JOKER")//Coringa
	,BADGE("PRODUCTION_STAFF_ROLE_BADGE")//Cracha
	,FINANCIAL("PRODUCTION_STAFF_ROLE_FINANCIAL")//Financeiro
	,FLIPCHART("PRODUCTION_STAFF_ROLE_FLIPCHART")//Flip Chart
	,PHOTO("PRODUCTION_STAFF_ROLE_PHOTO")//Fotografia
	,HOSTESS("PRODUCTION_STAFF_ROLE_HOSTESS")//Hostess
	,LIGHT("PRODUCTION_STAFF_ROLE_LIGHT")//Luzes
	,MEDICAMENT("PRODUCTION_STAFF_ROLE_MEDICAMENT")//Medicamentos
	,MICROPHONE("PRODUCTION_STAFF_ROLE_MICROPHONE")//Microfone
	,CHAIR("PRODUCTION_STAFF_ROLE_CHAIR")//Organizador Cadeiras
	,ROOM("PRODUCTION_STAFF_ROLE_ROOM")//Organizado Salao
	,DOOR("PRODUCTION_STAFF_ROLE_DOOR")//Porta
	,VIDEO("PRODUCTION_STAFF_ROLE_VIDEO")//Projecao Imagens e Videos
	,REPORT("PRODUCTION_STAFF_ROLE_REPORT")//Informes
	,SOUND("PRODUCTION_STAFF_ROLE_SOUND")//Som
	,TIMER("PRODUCTION_STAFF_ROLE_TIMER")//Timer
	
	;
	
	
	private String key;
	
	private StaffRole(String key){
		this.key = key;
	}

	public String getKey() {
		return key;
	}
	
	

}
